### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by gingyneil**

### CODE REVIEW

**Comment by gingyneil** [comment]
Code seems to work fine, run some Jclip tests and last thing to do is clean up/format the code. _We should not have merged to master yet_ - Arlina. Oops -Neil

**Comment by JClipperton** [comment]
Tester J to the scene @aajn3/programming3 

Bugs _(in order of severity)_
- [ ] On fail; **program does not display fail message**
- [ ] On fail; **GUI does not update score/lives to 0**
- [ ] On win; requirements state "display score/lives on win", we have that, but maybe **concat remaining score and lives to winMessage**
- [ ] On label select; **single guess can be clicked multiple times** (feature for the simple minded?)

**Comment by aramrattan** [comment]
did anyone do this?

**Comment by aramrattan** [comment]
I am closing this merge until the fixes are done. Please merge to develop until we are 99% sure that we have done all the requirements.

**Pull request closed without merging**
